// swift-tools-version: 6.3
import PackageDescription

let package = Package(
    name: "swift-harness",
    platforms: [.macOS(.v26)],
    products: [
        .library(name: "HarnessCore", targets: ["HarnessCore"]),
        .library(name: "WebUI", targets: ["WebUI"]),
        .executable(name: "dsh", targets: ["DSHCLI"]),
        .executable(name: "HarnessApp", targets: ["HarnessApp"]),
        .executable(name: "MemProbe", targets: ["MemProbe"]),
    ],
    dependencies: [
        .package(url: "https://github.com/apple/swift-argument-parser.git", from: "1.3.0"),
        .package(url: "https://github.com/apple/swift-log.git", from: "1.6.0"),
        .package(url: "https://github.com/apple/swift-collections.git", from: "1.1.0"),
        .package(url: "https://github.com/groue/GRDB.swift.git", from: "7.11.1"),
    ],
    targets: [
        // Core
        .target(name: "ServiceContainer",
                dependencies: [.product(name: "Logging", package: "swift-log")],
                path: "Packages/ServiceContainer/Sources"),
        .testTarget(name: "ServiceContainerTests",
                    dependencies: ["ServiceContainer"],
                    path: "Packages/ServiceContainer/Tests"),

        .target(name: "Session",
                dependencies: ["ServiceContainer", .product(name: "GRDB", package: "GRDB.swift")],
                path: "Packages/Session/Sources"),
        .testTarget(name: "SessionTests",
                    dependencies: ["Session", "ServiceContainer"],
                    path: "Packages/Session/Tests"),

        .target(name: "LLM",
                dependencies: ["ServiceContainer"],
                path: "Packages/LLM/Sources"),
        .testTarget(name: "LLMTests",
                    dependencies: ["LLM"],
                    path: "Packages/LLM/Tests"),

        .target(name: "Tools",
                dependencies: ["ServiceContainer", "Session", "LLM", "Terminal", "Sandbox"],
                path: "Packages/Tools/Sources"),
        .testTarget(name: "ToolsTests",
                    dependencies: ["Tools", "ServiceContainer", "Session", "LLM", "Terminal", "Sandbox", "Agent"],
                    path: "Packages/Tools/Tests"),

        .target(name: "Agent",
                dependencies: ["ServiceContainer", "Session", "LLM", "Tools"],
                path: "Packages/Agent/Sources"),
        .testTarget(name: "AgentTests",
                    dependencies: ["Agent", "Session", "LLM", "Tools"],
                    path: "Packages/Agent/Tests"),

        .target(name: "WebUI",
                dependencies: ["ServiceContainer", "Session", "LLM", "Agent", "Tools"],
                path: "Packages/WebUI/Sources"),
        .testTarget(name: "WebUITests",
                    dependencies: ["WebUI", "Session", "LLM", "Agent", "Tools"],
                    path: "Packages/WebUI/Tests"),

        .target(name: "Prompt",
                dependencies: ["ServiceContainer"],
                path: "Packages/Prompt/Sources"),
        .testTarget(name: "PromptTests",
                    dependencies: ["Prompt", "ServiceContainer"],
                    path: "Packages/Prompt/Tests"),

        .target(name: "RAG",
                dependencies: ["ServiceContainer", "Tools"],
                path: "Packages/RAG/Sources"),
        .testTarget(name: "RAGTests",
                    dependencies: ["RAG", "ServiceContainer", "Tools", "Session"],
                    path: "Packages/RAG/Tests"),

        .target(name: "Memory",
                dependencies: ["RAG", "Tools", "Session"],
                path: "Packages/Memory/Sources"),
        .testTarget(name: "MemoryTests",
                    dependencies: ["Memory", "RAG", "Tools", "Session"],
                    path: "Packages/Memory/Tests"),

        .target(name: "HarnessCore",
                dependencies: ["ServiceContainer", "Session", "LLM", "Tools", "Agent"],
                path: "Apps/HarnessCore/Sources"),

        .executableTarget(name: "DSHCLI",
                          dependencies: ["HarnessCore", "Agent", "Subagent", "LLM", "Tools", "ServiceContainer", "Session",
                                         "Skill", "WebUI", "Prompt", "MCP", "RAG", "Memory", .product(name: "ArgumentParser", package: "swift-argument-parser")],
                          path: "Apps/DSHCLI/Sources"),

        // 内存/性能探针
        .executableTarget(name: "MemProbe",
                          dependencies: ["ServiceContainer", "Session", "LLM", "Tools"],
                          path: "Apps/MemProbe/Sources"),

        // macOS App
        .executableTarget(name: "HarnessApp",
                          dependencies: ["HarnessCore", "ServiceContainer", "Session", "LLM", "Tools", "Agent",
                                         "Subagent", "MCP", "Terminal", "Sandbox", "Notifications", "PluginXPC",
                                         "Skill", "Prompt", "RAG", "Memory", "Workspace"],
                          path: "Apps/HarnessApp/Sources"),
        .testTarget(name: "HarnessAppTests",
                    dependencies: ["HarnessApp", "Agent", "Subagent", "Session", "LLM", "Tools"],
                    path: "Apps/HarnessApp/Tests"),

        // Extended
        .target(name: "Notifications",
                dependencies: ["ServiceContainer"],
                path: "Packages/Notifications/Sources"),
        .testTarget(name: "NotificationsTests",
                    dependencies: ["Notifications"],
                    path: "Packages/Notifications/Tests"),

        .target(name: "PluginXPC",
                dependencies: ["ServiceContainer"],
                path: "Packages/PluginXPC/Sources"),
        .testTarget(name: "PluginXPCTests",
                    dependencies: ["PluginXPC", "ServiceContainer"],
                    path: "Packages/PluginXPC/Tests"),

        // XPC 插件 worker（launchd 按需拉起，崩溃隔离）
        .executableTarget(name: "HarnessPluginWorker",
                          dependencies: ["PluginXPC", "HarnessCore", "ServiceContainer"],
                          path: "Apps/HarnessPluginWorker/Sources"),

        .target(name: "Workspace",
                dependencies: ["ServiceContainer", "Session"],
                path: "Packages/Workspace/Sources"),
        .testTarget(name: "WorkspaceTests",
                    dependencies: ["Workspace", "Session"],
                    path: "Packages/Workspace/Tests"),
        .target(name: "Goal",
                dependencies: ["ServiceContainer", "Session"],
                path: "Packages/Goal/Sources"),
        .target(name: "Plan",
                dependencies: ["ServiceContainer", "Goal"],
                path: "Packages/Plan/Sources"),
        .target(name: "Skill",
                dependencies: ["ServiceContainer", "Tools", "RAG"],
                path: "Packages/Skill/Sources"),
        .testTarget(name: "SkillTests",
                    dependencies: ["Skill", "Tools", "Session", "RAG"],
                    path: "Packages/Skill/Tests"),
        .target(name: "MCP",
                dependencies: ["ServiceContainer", "Tools"],
                path: "Packages/MCP/Sources"),
        .testTarget(name: "MCPTests",
                    dependencies: ["MCP", "ServiceContainer", "Tools", "Session"],
                    path: "Packages/MCP/Tests"),
        .target(name: "Subagent",
                dependencies: ["ServiceContainer", "Agent", "Session", "LLM", "Tools"],
                path: "Packages/Subagent/Sources"),
        .testTarget(name: "SubagentTests",
                    dependencies: ["Subagent", "Agent", "LLM", "Tools", "Session"],
                    path: "Packages/Subagent/Tests"),
        .target(name: "Sandbox",
                dependencies: ["ServiceContainer"],
                path: "Packages/Sandbox/Sources"),
        .testTarget(name: "SandboxTests",
                    dependencies: ["Sandbox"],
                    path: "Packages/Sandbox/Tests"),
        .target(name: "Terminal",
                dependencies: ["ServiceContainer"],
                path: "Packages/Terminal/Sources"),
        .testTarget(name: "TerminalTests",
                    dependencies: ["Terminal"],
                    path: "Packages/Terminal/Tests"),
        .testTarget(name: "HarnessCoreTests",
                    dependencies: ["HarnessCore"],
                    path: "Apps/HarnessCore/Tests"),
    ]
)
